In [142]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [143]:
url = "https://storage.googleapis.com/download.tensorflow.org/data/heart.csv"

df = pd.read_csv(url)

In [144]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,1,145,233,1,2,150,0,2.3,3,0,fixed,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,normal,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2,reversible,0
3,37,1,3,130,250,0,0,187,0,3.5,3,0,normal,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,normal,0

In [145]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    object
 13  target    303 non-null    int64
dtypes: float64(1), int64(12), object(1)
memory usage: 33.3+ KB

In [147]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [148]:
X = df.drop("target", axis=1)

y = df["target"]

In [149]:
from sklearn.model_selection import train_test_split

In [150]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [151]:
from sklearn.linear_model import LogisticRegression

In [152]:
model = LogisticRegression()

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    object
 13  target    303 non-null    int64
dtypes: float64(1), int64(12), object(1)
memory usage: 33.3+ KB

In [154]:
object

object

In [155]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = le.fit_transform(df[column])

In [156]:
X = df.drop("target", axis=1)

y = df["target"]

In [157]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [158]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [159]:
y_pred = model.predict(X_test)

In [160]:
print(y_pred)

[1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1
 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0]

In [161]:
from sklearn.metrics import accuracy_score

In [162]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8360655737704918

In [163]:
from sklearn.metrics import confusion_matrix

In [164]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[39  5]
 [ 5 12]]

In [165]:
from sklearn.metrics import classification_report

In [166]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        44
           1       0.71      0.71      0.71        17

    accuracy                           0.84        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.84      0.84      0.84        61

In [167]:
from sklearn.ensemble import RandomForestClassifier

In [168]:
rf_model = RandomForestClassifier()

In [169]:
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [170]:
rf_pred = rf_model.predict(X_test)

In [171]:
rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.819672131147541

In [172]:
sample_data = [X.iloc[0].values]

In [173]:
prediction = rf_model.predict(sample_data)

print(prediction)

[0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [174]:
if prediction[0] == 1:
    print("Disease Detected")
else:
    print("No Disease Detected")

No Disease Detected

In [175]:
print("Logistic Regression Accuracy:", accuracy)

print("Random Forest Accuracy:", rf_accuracy)

Logistic Regression Accuracy: 0.8360655737704918
Random Forest Accuracy: 0.819672131147541

In [176]:
rf_model

RandomForestClassifier()

Heart Disease Prediction using Machine Learning

This project predicts whether a person has heart disease or not using Machine Learning algorithms like Logistic Regression and Random Forest.

Project Workflow:
1. Import Libraries
2. Load Dataset
3. Data Preprocessing
4. Train-Test Split
5. Train Models
6. Evaluate Accuracy
7. Final Prediction System